### get all events
GET http://localhost:3001/api/v1/getallevents

### get events ( search, city category, access, order )
# http://localhost:3001/api/v1/getallevents?search=&city=&category=&access=&order=

# GET http://localhost:3001/api/v1/getallevents?search=conference&city=&category=&access=&order=

# GET http://localhost:3001/api/v1/getallevents?search=&city=Paris&category=&access=&order=

# GET http://localhost:3001/api/v1/getallevents?search=&city=Paris&category=Food&access=&order=

# GET http://localhost:3001/api/v1/getallevents?search=&city=Paris&category=Food&access=free&order=

# GET http://localhost:3001/api/v1/getallevents?search=&city=Paris&category=Food&access=paid&order=ASC

# GET http://localhost:3001/api/v1/getallevents?search=&city=&category=Food&access=&order=

# GET http://localhost:3001/api/v1/getallevents?search=&city=&category=Food&access=free&order=

# GET http://localhost:3001/api/v1/getallevents?search=&city=&category=Food&access=paid&order=DESC

# GET http://localhost:3001/api/v1/getallevents?search=&city=&category=&access=free&order=
# GET http://localhost:3001/api/v1/getallevents?search=&city=&category=&access=&order=